//! Mapping simulation facts onto Kafka.
//!
//! The core produces `sim::DomainEvent` and has no idea Kafka exists. This is
//! where those facts become `pips.events.v1.EventEnvelope` and get a topic, a
//! partition key and a trace id.
//!
//! Two rules from the ADRs are enforced here:
//!
//! - The partition key is always the aggregate id, so one pip's events keep
//!   their relative order. Ordering is only guaranteed within a partition, so a
//!   key chosen per-message rather than per-entity would silently interleave a
//!   single pip's history.
//! - Kafka carries the envelope, never a bare payload. The envelope is what
//!   makes replay and cross-service tracing possible.

use std::time::SystemTime;

use rdkafka::producer::{FutureProducer, FutureRecord};
use rdkafka::util::Timeout;
use sim::DomainEvent;

use crate::telemetry;

pub mod pb {
    // Generated by build.rs from proto/. Rust is the one language with nothing
    // in gen/ — see gen/README.md. The nesting mirrors the proto packages
    // exactly, because prost emits cross-package references as `super::` paths.
    include!(concat!(env!("OUT_DIR"), "/pipsim.rs"));
}

use pb::pips::events::v1::{
    event_envelope::Payload, EventEnvelope, PipDied, PipGotHungry, PipSpawned, PipStartedWork,
};
use pb::pips::sim::v1 as simpb;

pub const TOPIC_LIFECYCLE: &str = "pipsim.pip.lifecycle.v1";
pub const TOPIC_WORK: &str = "pipsim.pip.work.v1";

/// Envelope plus its routing decision: which topic, and which key.
struct Routed {
    topic: &'static str,
    key: String,
    envelope: EventEnvelope,
}

fn now_timestamp() -> prost_types::Timestamp {
    let d = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default();
    prost_types::Timestamp {
        seconds: d.as_secs() as i64,
        nanos: d.subsec_nanos() as i32,
    }
}

fn route(tick: u64, event: &DomainEvent) -> Routed {
    let (topic, key, payload) = match event {
        DomainEvent::PipSpawned {
            pip,
            name,
            position,
        } => (
            TOPIC_LIFECYCLE,
            pip.to_string(),
            Payload::PipSpawned(PipSpawned {
                pip_id: *pip,
                name: name.clone(),
                position: Some(simpb::Vec2 {
                    x_milli: position.x,
                    y_milli: position.y,
                }),
            }),
        ),
        DomainEvent::PipGotHungry { pip, food_level } => (
            TOPIC_LIFECYCLE,
            pip.to_string(),
            Payload::PipGotHungry(PipGotHungry {
                pip_id: *pip,
                food_level: *food_level,
            }),
        ),
        DomainEvent::PipDied { pip, cause } => (
            TOPIC_LIFECYCLE,
            pip.to_string(),
            Payload::PipDied(PipDied {
                pip_id: *pip,
                cause: (*cause).to_string(),
                age_ticks: 0,
            }),
        ),
        DomainEvent::PipStartedWork { pip, workplace } => (
            TOPIC_WORK,
            pip.to_string(),
            Payload::PipStartedWork(PipStartedWork {
                pip_id: *pip,
                workplace_id: *workplace,
                workplace_kind: String::new(),
            }),
        ),
    };

    Routed {
        topic,
        key,
        envelope: EventEnvelope {
            // UUIDv7 sorts by creation time, so a consumer deduplicating on this
            // gets useful locality for free.
            event_id: uuid::Uuid::now_v7().to_string(),
            // The tick, not the wall clock, is the ordering authority. The
            // timestamp below is for humans reading the console.
            tick,
            occurred_at: Some(now_timestamp()),
            trace_id: telemetry::current_trace_id(),
            producer: telemetry::SERVICE_NAME.to_string(),
            payload: Some(payload),
        },
    }
}

/// Publishes a tick's worth of facts.
///
/// Delivery is fire-and-forget with a zero timeout: this sits inside the tick
/// loop, and blocking the simulation on a broker acknowledgement would let
/// Kafka backpressure dictate the simulation rate. Losing an event is a
/// monitoring problem; stalling the world is a gameplay one.
pub async fn publish(producer: &FutureProducer, tick: u64, events: &[DomainEvent]) -> usize {
    use prost::Message;

    let mut sent = 0;
    for event in events {
        let routed = route(tick, event);
        let mut buf = Vec::with_capacity(routed.envelope.encoded_len());
        if routed.envelope.encode(&mut buf).is_err() {
            tracing::error!(topic = routed.topic, "failed to encode envelope");
            continue;
        }

        let record: FutureRecord<String, Vec<u8>> = FutureRecord::to(routed.topic)
            .key(&routed.key)
            .payload(&buf);

        match producer
            .send(record, Timeout::After(std::time::Duration::ZERO))
            .await
        {
            Ok(_) => sent += 1,
            Err((err, _)) => {
                tracing::warn!(topic = routed.topic, error = %err, "publish failed");
            }
        }
    }
    sent
}
